version: '3'

services:
    nginx:
        image: nginx:1.9
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "5000:5000"
        volumes:
            - ./php/src:/var/www/backend
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - pgsql

        networks:
            - mynetwork

    pgsql:
        image: timescale/timescaledb-ha:pg14-latest
        container_name: pgsql
        restart: always
        tty: true
        ports:
            - 5432:5432
        volumes:
            - ./pgsql/postgresql.conf:/etc/postgresql/14/main/postgresql.conf
            - ./pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - mynetwork

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: always
        tty: true
        working_dir: /var/www/backend
        volumes: 
            - ./php/src:/var/www/backend
        ports:
            - "9000:9000"
        networks:
            - mynetwork

volumes:
    postgres_data:

networks:
    mynetwork:
        driver: bridge