version: '3'

services:
    nginx:
        image: nginx:1.9
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "6000:6000"
        volumes:
            - ./php/src:/var/www/backend
            - ./nginx/backend.conf:/etc/nginx/sites-available/backend
        depends_on:
            - php
            - pgsql

        networks:
            - mynetwork

    pgsql:
        image: postgres:14
        container_name: pgsql
        restart: always
        tty: true
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DATABASE=laravel
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_ROOT_PASSWORD=root
        volumes:
            - ./:/var/lib/postgressql/data
            - ./pgsql/postgresql.conf:/etc/postgresql/14/main/postgresql.conf
        networks:
            - mynetwork

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: always
        tty: true
        working_dir: /var/www/backend
        volumes: 
            - ./php/src:/var/www/backend
        ports:
            - "9000:9000"
        networks:
            - mynetwork

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - .:/var/www/backend
        command: install        

volumes:
    postgres_data:

networks:
    mynetwork:
        driver: bridge