---
- hosts: srv1
  become: true

  tasks:
    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /home/docker/stack/docker/
        files:
          - docker-compose.yml