---
- hosts: {server-hostname}
  become: true

  tasks:
    - name: Clone Docker Project 
      git:
        repo: https://github.com/danielcristho/laravel-pgsql-nginx.git
        clone: yes 
        dest: /home/docker/project
        update: yes

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /home/docker/project/docker/
        files:
          - docker-compose.yml
