---
- hosts: srv1
  become: true

  tasks:
    - name: Clone Docker Project 
      git:
        repo: https://github.com/danielcristho/laravel-pgsql-nginx.git
        clone: yes 
        dest: /home/docker/
        update: yes

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /home/docker/stack
        files:
          - docker-compose.yml
